# 수 자료형
- 정수를 기본으로 사용

## 정수형
- 정수를 다루는 자료형
- 정수형에는 양의 정수, 음의 정수, 0이 있음

In [1]:
a = 1000
print(a)


a = -7
print(a)

a = 0
print(a)

1000
-7
0


## 실수형

In [2]:
a = 157.93
print(a)

a = -1837.2
print(a)

a = 5.
print(a)

a = -7.
print(a)

157.93
-1837.2
5.0
-7.0


- 실수형 데이터를 표현하는 방식으로 파이썬에서는 e나 E를 이용한 지수 표현 방식을 이용
- e 다음에 오는 수는 10의 지수부를 의미

In [3]:
# 10억의 지수 표현 방식
a = 1e9
print(a)

# 752.5
a = 75.24e1
print(a)

# 3.954
a = 3954e-3
print(a)

1000000000.0
752.4
3.954


- 컴퓨터가 실수를 정확히 표현하지 못한다는 사실을 기억!

In [4]:
a = 0.3 + 0.6
print(a)

if a == 0.9:
    print(True)
else :
    print(False)

0.8999999999999999
False


- 소수점 값을 비교하는 작업이 필요한 문제라면 round()함수 이용하기

In [6]:
a = 0.3 + 0.6
print(round(a,3))

if round(a,4) == 0.9:
    print(True)
else :
    print(False)

0.9
True


In [7]:
[True if round(a,4) == 0.9 else print(False)]

[True]

In [8]:
True if round(a,4) == 0.9 else print(False)

True

## 수 자료형의 연산

- 파이썬에서는 나누기 연산자(/)는 나눠진 결과를 기본적으로 실수형으로 처리 함

In [9]:
a ,b = 7,3

print(a/b)

print(a % b)

print(a // b)

2.3333333333333335
1
2


In [10]:
print(a ** b)

343


# 리스트 자료형
- 리스트는 여러 개의 데이터를 연속적으로 담아 처리하기 위해 사용
- append(), remove() 등의 메서드 지원

## 리스트 만들기
- 리스트는 대괄호([])안에 원소를 넣어 초기화하며 쉽표로 원소를 구분
- 인덱스는 0부터 시작
- 비어있는 리스트를 선언하고자 할 때는 list() 혹은 간단히 대괄호([])를 이용

In [13]:
a = [1,2,3,4,5,6,7,8,9]
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [14]:
print(a[4])

5


In [15]:
a = list()
print(a)

[]


In [16]:
a = []
print(a)

[]


- 코딩 테스트 문제에서는 주로 크기가 N인 1차원 리스트를 초기화해야 하는데 다음 방식으로 초기화하면 편리함!

In [17]:
# 크기가 N이고, 모든 값이 0인 1차원 리스트 초기화
n = 10
a = [0] * n
print(a)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [18]:
[0] * 10

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [19]:
[1,2,3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

- 인덱스값을 입력하여 리스트의 특정한 원소에 접근하는 것을 인덱싱
- 파이썬의 인덱스값은 양의 정수와 음의 정수를 모두 사용할 수 있으며, 음의 정수를 넣으며 원소를 거꾸로 탐색

In [20]:
a = [1,2,3,4,5,6,7,8,9]
print(a[-1])

print(a[-3])

# 네번째 원소 값 변경
a[3] = 7
print(a)

9
7
[1, 2, 3, 7, 5, 6, 7, 8, 9]


- 리스트에서 연속적인 위치를 갖는 원소들을 가져와야 할 떄는 슬라이싱 이용
- 대괄호 안에 콜론을 넣어서 시작 인덱스와 끝 인덱스를 설정할 수 있음

In [21]:
print(a[1:4])

[2, 3, 7]


## 리스트 컴프리헨션
- 매우 매우 매우 중요한 듯... 데이콘에서도 전처리 할 때 많이 쓰임! 익혀두자
- 리스트 컴프리헨션은 리스트를 초기화하는 방법 중 하나
- 리스트 컴프리헨션을 이용하면 대괄호안에 조건문과 반복문을 넣는 방식으로 시트를 초기화할 수 있음


In [22]:
# 0 부터 19까지의 수 중에서 홀수만 포함하는 리스트

array = [i for i in range(20) if i % 2 == 1]

print(array)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [23]:
# 위 코드를 반복문으로 해보자

array = []
for i in range(20):
    if i % 2 == 1:
        array.append(i)
        
print(array)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [26]:
# 1부터 9까지의 수의 제곱 값을 포함하는 리스트

array = [i*i for i in range(1,10)]

print(array)

[1, 4, 9, 16, 25, 36, 49, 64, 81]


- 이러한 리스트 컴프리헨션은 코딩 테스트에서 2차원 리스트를 초기화 할 때 매우 효과적으로 사용도리 수 있음

In [28]:
# n * m 크기의 2차원 리스트 초기화 

n = 3
m = 4
array = [[0] for _ in range(n)]
print(array)


array = [[0] * m for _ in range(n)]
print(array)

[[0], [0], [0]]
[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]


* 언더바(_)는 어떤 역할?
    - 파이썬 자료구조/알고리즘에서는 반복을 수행하되 반복을 위한 변수의 값을 무시하고자 할 때 언더바(_)를 자주 사용
    - 예를 들어 1부터 9까지의 자연수를 더할 때는 아래처럼 작성. 
    - 단순히 "Hello World"를 5번 출력할 때는 언더바(_)를 이용하여 무시

In [40]:
summary = 0
for i in range(1,10):
    summary += i
print(summary)

45


In [41]:
for _ in range(5):
    print("Hello World")

Hello World
Hello World
Hello World
Hello World
Hello World


* 참고로 특정 크기의 2차원 리스트를 초기화할 때는 반드시 리스트 컴프리헨션을 이용해야 함
* 만약에 다음과 같이 N * M 크기의 2차원 리스트를 초기화한다면, 의도치 않은 결과가 나올 수 있음

In [42]:
n = 3
m = 4
array = [[0] *m ] *n
print(array)

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]


In [43]:
array[1][1] = 5
print(array)

[[0, 5, 0, 0], [0, 5, 0, 0], [0, 5, 0, 0]]


- 따라서 특정한 크기를 가지는 2차원 리스트를 초기화할 떄에는 리스트 컴프리헨션을 이용해야 한다는 점을 기억
- numpy 배열로 바꿔주면 되는구나!

In [46]:
import numpy as np

a = np.array([[0] * m] * n)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [47]:
a[1][1] = 5
print(a)

[[0 0 0 0]
 [0 5 0 0]
 [0 0 0 0]]


## 리스트 관련 기타 메서드

In [48]:
a = [1,4,3]
print("기본 리스트 : ", a)


기본 리스트 :  [1, 4, 3]


In [49]:
# 리스트에 원소 삽입 append
# 끝에 삽입됨
a.append(2)
print("삽입 : " ,a)

삽입 :  [1, 4, 3, 2]


In [50]:
# 오름차순 정렬
a.sort()
print("오름차순 : ", a)

오름차순 :  [1, 2, 3, 4]


In [51]:
# 내림차순 정렬
a.sort(reverse = True)
print("내림차순 : " , a)

내림차순 :  [4, 3, 2, 1]


In [52]:
# 리스트 원소 뒤집기
a.reverse()
print("원소 뒤집기 : ", a)

원소 뒤집기 :  [1, 2, 3, 4]


In [53]:
# 특정 인덱스에 데이터 추가
a.insert(2,3)
print("인덱스 2에 3추가 : ", a)

인덱스 2에 3추가 :  [1, 2, 3, 3, 4]


In [54]:
# 특정 값인 데이터 개수 세기
print("값이 3인 데이터 개수 : " , a.count(3))

값이 3인 데이터 개수 :  2


In [55]:
# 특정 값 데이터 삭제
a.remove(1)
print("값이 1인 데이터 삭제 : ", a)

값이 1인 데이터 삭제 :  [2, 3, 3, 4]


- inset()함수와 append(), remove()를 기억해두자!
- append() 함수는 O(1) 에 수행되는데 반해 insert()함수와 remove()의 시간 복잡도는 O(N)으로 시간 초과가 일어날 수 있음!

-- 특정한 값의 원소를 모두 제거하는 방법!

In [57]:
a = [1,2,3,4,5,5,5]
remove_set = [3,5]

# remove_set에 포함되지 않은 값만을 저장

result = [i for i in a if i not in remove_set]
print(result)


[1, 2, 4]


In [60]:
type({3,5,3})

set

In [59]:
type([3,5])

list

# 문자열 자료형
## 문자열 초기화
- 문자열 변수를 초기화 할 때는 큰따옴표나 작은따옴표 이용

In [62]:
data = "Hello World"
print(data)

data = "Don't you know \"Python\"?"
print(data)

Hello World
Don't you know "Python"?


In [64]:
a = "Hello"
b = "World"
print(a + " " + b)

Hello World


In [65]:
a = "String"

print(a * 3)

StringStringString


In [66]:
a = "ABCDEF"
print(a[2:4])

CD


# 튜플 자료형
## 튜플과 리스트의 차이점
- 튜플은 한 번 선언된 값을 변경할 수 없음
- 리스트는 대괄호를 이용하지만 튜플은 소괄호 이용

예를 들어 하나의 튜플 데이터를 선언한 다음, 값을 출력하고 튜플의 특정한 값을 변경


In [67]:
a = (1,2,3,4)
print(a)



(1, 2, 3, 4)


In [68]:
# 튜플은 값을 변경할 수 없으므로 오류가 남

a[2] = 7

TypeError: 'tuple' object does not support item assignment